# Generated by Django 4.2.5 on 2023-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('vendor', models.CharField(choices=[('Mikrotik', 'Mikrotik'), ('Cisco', 'Cisco')], max_length=255)),
            ],
        ),
    ]
